### ISSUE TITLE
plugin doesn't work when combined with rollup-plugin-terser

### ISSUE THREAD

**Issue by TimmyTango** [straker/rollup-plugin-kontra#5]
First off, I'm a rollup newbie. I only grabbed it because parcel's bundles were too big, even with tree-shaking.

I noticed that when I tried to use this plugin in my project, it didn't change the size of the output at all. I did some digging and found that `generateBundle`, the hook this plugin uses, is one of the last hooks to run. By the time the code gets to that point, the terser plugin (rollup-plugin-terser), had already removed all of the comments needed for the preprocess library. If I disabled the terser plugin, the karma plugin would work as expected.

I took a very naive approach and swapped the `generateBundle` hook with a `transform` hook. This ran before the hooks that terser uses and produced the result I was looking for.

Here is my naive way of doing it:

```js
transform(code, id) {
    if (id.includes('kontra.js') || id.includes('kontra.mjs')) {
        return pp.preprocess(code, flatten(options), {type: 'js'});
    }
    return null;
}
```

There might be better ways of handling this, which is why I'm not submitting a PR. I don't know enough about the internals of rollup to know if I made a huge mistake. It's working with my project so far, and saved me 1.4k on the zip bundle.

**Comment by straker** [comment]
Thanks for letting me know. This is my first rollup plugin so I'll have to look more closely at the hooks and which one to use better.

**Comment by straker** [comment]
So looking at the hooks the plugins are suppose to run in the order provided by the rollup config when the hooks are the same. If you use the `renderChunck` hook but place rollup-plugin-kontra before tersers, does that still work?

**Comment by TimmyTango** [comment]
Yep, that works!

```js
function flatten(obj, prefix = '') {
    ...
}

export default function (options = {}) {
    return {
        name: 'my-test-plugin',
        renderChunk(code, chunk, outputOptions) {
            return pp.preprocess(code, flatten(options), { type: 'js' });
        }
    }
}
```

**Comment by straker** [comment]
K. I'll update the code to use `renderChunk` and see about making sure sourcemaps are possible as well.

**Comment by straker** [comment]
So it seems sourcemaps aren't possible with preprocess as [it doesn't support them](https://github.com/jsoverson/preprocess/issues/59).

**Comment by straker** [comment]
v1.0.1 published with fix https://www.npmjs.com/package/rollup-plugin-kontra/v/1.0.1
